import BentPartitionDepth.Definitions
import BentPartitionDepth.CyclotomicMultiplicity
import BentPartitionDepth.DoubleCounting
import BentPartitionDepth.WalshDerivative
import BentPartitionDepth.Main
